package team.jndk.praktyki.praktyki_spring.model.data;

import jakarta.persistence.*;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;

@Table(name = "YTVideos")
@Entity
public class YTVideo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", columnDefinition = "INT GENERATED BY DEFAULT AS IDENTITY")
    private Integer id;

    @NotBlank
    private String title;
    @NotBlank
    @Column(name = "google_vid_id", unique = true)
    private String googleId;
    @Min(0)
    private int likes;
    @Min(0)
    private int comments;
    @Min(0)
    private int views;
    @Column(name = "scanned_date")
    private long scannedDate;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "chan_id")
    @JsonBackReference
    private Channel channel;

    public YTVideo(String title, String videoId, int likes, int comments, int views, long scannedDate) {
        this.title= title;
        this.googleId = videoId;
        this.views = views;
        this.likes = likes;
        this.comments = comments;
        this.scannedDate = scannedDate;
    }

    public YTVideo() {

    }


    @Override
    public String toString() {
        return "Video{" +
                "title='" + title + "'\n" +
                ", id='" + googleId + "'\n" +
                ", views=" + views + "'\n" +
                ", likes=" + likes + "'\n" +
                ", comments=" + comments + "'\n" +
                ", scannedDate='" + new Date(scannedDate).toGMTString() +
                "}\n\n";
    }

    // Jawne metody dostępowe (gettery/setter) wymagane przez serwisy
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGoogleId() {
        return googleId;
    }

    public void setGoogleId(String googleId) {
        this.googleId = googleId;
    }

    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }

    public int getComments() {
        return comments;
    }

    public void setComments(int comments) {
        this.comments = comments;
    }

    public int getViews() {
        return views;
    }

    public void setViews(int views) {
        this.views = views;
    }

    public long getScannedDate() {
        return scannedDate;
    }

    public void setScannedDate(long scannedDate) {
        this.scannedDate = scannedDate;
    }

    public Channel getChannel() {
        return channel;
    }

    public void setChannel(Channel channel) {
        this.channel = channel;
    }
}
